# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f5407a1dccb137d3cfa772f4c768b9b8fb8e5ab815dafdd6922142803554698a7e762fa9fbcd4a4efd23fa0fbff85b2c6f7edae3fee29d8a9feae95584e02f7

test:
  secret_key_base: e9dfe3af2a97f3632efa98b8d556c62013cb9319b814a0322980530c80b4e5b296d228812c029b86a9800aa66166965a2b9dfb64a1308460cb5daede9819071e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
